font_family      family="IosevkaTerm Nerd Font" style=Regular
bold_font        family="IosevkaTerm Nerd Font" style='Extrabold'
italic_font      family="IosevkaTerm Nerd Font" style='Italic'
bold_italic_font family="IosevkaTerm Nerd Font" style='Extrabold Italic'
