os:
  editPreset: "nvim-remote"
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#46d9ff"
      - "bold"
    inactiveBorderColor:
      - "#5b6268"
    searchingActiveBorderColor:
      - "#46d9ff"
      - "bold"
    optionsTextColor:
      - "#3071db"
    selectedLineBgColor:
      - "#282c34"
    cherryPickedCommitFgColor:
      - "#3071db"
    cherryPickedCommitBgColor:
      - "#ff6c6b"
    markedBaseCommitFgColor:
      - "#3071db"
    markedBaseCommitBgColor:
      - "#da8548"
    unstagedChangesColor:
      - "#ff6c6b"
    defaultFgColor:
      - "#bbc2cf"
    # ===
    # # Astrodark
    # activeBorderColor:
    #   - "#50A4E9"
    #   - "bold"
    # inactiveBorderColor:
    #   - "#3A3E47"
    # searchingActiveBorderColor:
    #   - "#50A4E9"
    #   - "bold"
    # optionsTextColor:
    #   - "#5EB7FF"
    # selectedLineBgColor:
    #   - "#26343F"
    # cherryPickedCommitFgColor:
    #   - "#1A1D23"
    # cherryPickedCommitBgColor:
    #   - "#DD97F1"
    # markedBaseCommitFgColor:
    #   - "#1A1D23"
    # markedBaseCommitBgColor:
    #   - "#DFAB25"
    # unstagedChangesColor:
    #   - "#FF838B"
    # defaultFgColor:
    #   - "#ADB0BB"
    # ===
    # activeBorderColor:
    #   - '#ffbd5e'
    #   - bold
    # inactiveBorderColor:
    #   - '#5ea1ff'
    # optionsTextColor:
    #   - '#5ea1ff'
    # selectedLineBgColor:
    #   - '#2e3138'
    # cherryPickedCommitBgColor:
    #   - '#ff9f9f'
    # cherryPickedCommitFgColor:
    #   - '#5ea1ff'
    # unstagedChangesColor:
    #   - '#ff6e5e'
    # defaultFgColor:
    #   - '#ffffff'
    # searchingActiveBorderColor:
    #   - '#ffbd5e'
    #   - bold
  authorColors:
    '*': '#ff5ea0'
git:
  autoForwardBranches: none
  paging:
    colorArg: always
    pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  # Config for showing the log in the commits view
