#!/bin/bash

if ! command -v gum choose >/dev/null 2>&1
then
    PICKER="fzf"
else
    PICKER="gum choose"
fi

SESSION=$(tmux list-sessions -F \#S | $PICKER)
tmux switch-client -t "$SESSION" || tmux attach -t "$SESSION"
