cursor #d3dae3
cursor_text_color #afb5bd

foreground            #d3dae3
background            #1c1f26
selection_foreground  #ffffff
selection_background  #6e87b0
url_color             #4b8cd8

color0   #1d2027
color1   #f8467a
color2   #4ad85e
color3   #fff547
color4   #4687e0
color5   #002e64
color6   #4b8cd8
color7   #d1d9e2
color8   #7e848c
color9   #ff82a7
color10  #8aff9a
color11  #fff88a
color12  #69a6ed
color13  #8ac0ff
color14  #b4d6ff
color15  #f6faff
